In [2]:
import numpy as np



In [16]:
#defining the goal matrix
test_puzzle_matrix = np.array([[0,2,3],[4,1,6],[7,8,5]])

In [5]:
#defining the goal matrix
goal_puzzle_matrix = np.array([[1,2,3],[4,5,6],[7,8,0]])
print(goal_puzzle_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [8]:
# function to calculate the location of the zero tile 
# and return the location as (i, j)

def BlankTileLocation(matrix):    
    for i in range(0,len(matrix)):
        for j in range(0,len(matrix)):            
            if (matrix[i][j] == 0):
                zero_row = i
                zero_column = j
    return zero_row, zero_column


In [9]:
BlankTileLocation(goal_puzzle_matrix)

(2, 2)

In [17]:
BlankTileLocation(test_puzzle_matrix)

(0, 0)