In [2]:
import numpy as np



In [3]:
#defining the goal matrix
test_puzzle_matrix = np.array([[1,2,3],[4,0,6],[7,8,5]])

In [4]:
#defining the goal matrix
goal_puzzle_matrix = np.array([[1,2,3],[4,5,6],[7,8,0]])
print(goal_puzzle_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [5]:
test = goal_puzzle_matrix.copy()
print(test)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [6]:
# function to calculate the location of the zero tile 
# and return the location as (i, j)

def BlankTileLocation(matrix):    
    for i in range(0,len(matrix)):
        for j in range(0,len(matrix)):            
            if (matrix[i][j] == 0):
                zero_row_number = i
                zero_column_number = j
    return zero_row_number, zero_column_number


In [34]:
# function to move the blank (zero) tile left
def ActionMoveLeft(matrix_zero_unmoved):
    matrix_zero_moved = matrix_zero_unmoved.copy()
    zero_row_number, zero_column_number = BlankTileLocation(matrix_zero_moved)
    
    if(zero_column_number>0):
        matrix_zero_moved[zero_row_number][zero_column_number] = matrix_zero_moved[zero_row_number][zero_column_number-1]
        matrix_zero_moved[zero_row_number][zero_column_number-1] = 0
        
    return matrix_zero_moved, matrix_zero_unmoved
        

In [35]:
# function to move the blank (zero) tile right
def ActionMoveRight(matrix_zero_unmoved):
    matrix_zero_moved = matrix_zero_unmoved.copy()
    zero_row_number, zero_column_number = BlankTileLocation(matrix_zero_moved)
    
    if(zero_column_number<len(matrix_zero_moved)-1):
        matrix_zero_moved[zero_row_number][zero_column_number] = matrix_zero_moved[zero_row_number][zero_column_number+1]
        matrix_zero_moved[zero_row_number][zero_column_number+1] = 0
        
    return matrix_zero_moved, matrix_zero_unmoved
        

In [36]:
# function to move the blank (zero) tile up
def ActionMoveUp(matrix_zero_unmoved):
    matrix_zero_moved = matrix_zero_unmoved.copy()
    zero_row_number, zero_column_number = BlankTileLocation(matrix_zero_moved)
    
    if(zero_row_number>0):
        matrix_zero_moved[zero_row_number][zero_column_number] = matrix_zero_moved[zero_row_number-1][zero_column_number]
        matrix_zero_moved[zero_row_number-1][zero_column_number] = 0
        
    return matrix_zero_moved, matrix_zero_unmoved
        

In [37]:
# function to move the blank (zero) tile down
def ActionMoveDown(matrix_zero_unmoved):
    matrix_zero_moved = matrix_zero_unmoved.copy()
    zero_row_number, zero_column_number = BlankTileLocation(matrix_zero_moved)
    
    if(zero_row_number<len(matrix_zero_moved)-1):
        matrix_zero_moved[zero_row_number][zero_column_number] = matrix_zero_moved[zero_row_number+1][zero_column_number]
        matrix_zero_moved[zero_row_number+1][zero_column_number] = 0
        
    return matrix_zero_moved, matrix_zero_unmoved
        
        
        
        
        
        
   

In [7]:
goal = np.array([1,2,3,4,5,6,7,8,0])

print(goal[2])
    
goalNode = [1, 2, 3, 4, 5, 6, 7, 8, 0]

print(goalNode[2])
    
    
    
    
    

3
3


In [ ]:
# Code to take initial state of the eight puzzle problem

def initial_state():
    print("Enter the initial state of the eight puzzle problem element wise")
    start_node = [0,0,0, 0,0,0, 0,0,0]
    for i in range(9):
        value = int(input("Enter the " + str(i+1) + "th value of the eight puzzle\n"))
        if value >8 or value<0:
            print("Enter a value from 0 to 8 only, Run program again please")
            exit(0)
          
        else:
            start_node[i] = value
            
    return start_node

         
            
    
    
    
            

In [ ]:
# Code to check for repetition of numbers

def repetition_check(node_for_check):
    for x in range(9):
        no_of_repetition = 0
        entry = node_for_check[x]
        for y in range(9):
            if entry == node_for_check[y]:
                no_of_repetition = no_of_repetition +1
             
    if no_of_repetition >= 1:
        print("An entry for the eight puzzle has been repeated, Please restart program")
        exit(0)

start_node = initial_state()
print("The initial state in row wise representation is  : ", start_node)    

repetition_check(start_node)


    

In [38]:
ActionMoveLeft(test_puzzle_matrix)

(array([[1, 2, 3],
        [0, 4, 6],
        [7, 8, 5]]), array([[1, 2, 3],
        [4, 0, 6],
        [7, 8, 5]]))

In [39]:
ActionMoveRight(test_puzzle_matrix)

(array([[1, 2, 3],
        [4, 6, 0],
        [7, 8, 5]]), array([[1, 2, 3],
        [4, 0, 6],
        [7, 8, 5]]))

In [40]:
ActionMoveUp(test_puzzle_matrix)

(array([[1, 0, 3],
        [4, 2, 6],
        [7, 8, 5]]), array([[1, 2, 3],
        [4, 0, 6],
        [7, 8, 5]]))

In [41]:
ActionMoveDown(test_puzzle_matrix)

(array([[1, 2, 3],
        [4, 8, 6],
        [7, 0, 5]]), array([[1, 2, 3],
        [4, 0, 6],
        [7, 8, 5]]))

In [7]:
zero_row_number, zero_column_number = BlankTileLocation(goal_puzzle_matrix)
print(zero_row_number, zero_column_number)



(2, 2)


In [16]:
len(test_puzzle_matrix)

3